/*  vote Plug-in
    Copyright (c) 2020 Cybozu
    Licensed under the MIT License  */
    let lang = {
        ja: {
            label_1: '条件と処理',
            label_2: '条件フィールドの色付け',
            description_1: 'フィールドの条件とあてはまる際の処理を設定します。複数の条件にあてはまる場合、上層の処理が優先されます。',
            description_2: '処理の条件元となるフィールドに背景色を付けます。',
            table_th_1: '条件',
            table_th_2: '処理',
            condition_all: 'すべてのレコード',
            condition_option_1: 'すべての条件を満たす',
            condition_option_2: 'いずれかの条件を満たす',
            method_item_1: '編集可',
            method_item_2: '編集不可',
            method_item_3: '表示',
            method_item_4: '非表示',
            button_add: '追加',
            button_dalete: '削除',
            coloring_option: '有効にする',
            button_submit: '保存する',
            button_cancel: 'キャンセル',
            equal_to:'=（等しい）',
            not_equal_to:'≠（等しくない）',
            less_than: '≦（以下）',
            greater_than: '≧（以上）',
            contain: '次のキーワードを含む',
            not_contain: '次のキーワードを含まない',
            select_in: '次のいずれかを含む',
            select_notin: '次のいずれも含まない',
            before: '<（より前）',
            on_or_before: '≦（以前）',
            after: '>（より後）',
            on_or_after: '≧（以降）',
            specify_date: '日時を指定',
            specify_from_date: '今日から',
            current: '当時刻',
            yesterday: '昨日',
            today: '今日',
            tomorrow: '明日',
            last_week: '先週',
            this_week: '今週',
            next_week: '来週',
            last_month: '先月',
            this_month: '今月',
            next_month: '来月',
            last_year: '去年',
            this_year: '今年',
            next_year: '来年',
            day: '日',
            week: '週',
            month: '月',
            year: '年',
            before_today: '前',
            after_today: '後',
            all_days: 'すべての曜日',
            sunday: '日',
            monday: '月',
            tuesday: '火',
            wednesday: '水',
            thursday: '木',
            friday: '金',
            saturday: '土',
            all: 'すべて',
            date: '日',
            last_day: '末日',
            selected: '選択中',
            ken: '件',
            user_placeholder: 'IDをコンマ区切りで指定',
            error1: '処理に空欄があります。',
            error2: '次のフィールドはdisabled出来ません。- 計算、グループ、サブテーブル、レコード番号、作成者、作成日時、更新者、更新日時',
            error3: 'サブテーブル内のフィールドはdisabled出来ません。'
        },
        en: {
            label_1: 'Condition and outcome',
            label_2: 'Conditional Field Background Coloring',
            description_1: 'Define the field conditions and the resulting outcome. When multiple conditions are met, the upper line outcome has priority.',
            description_2: 'Toggle this checkbox to add a background color to fields if they are used as conditions.',
            table_th_1: 'Condition',
            table_th_2: 'Outcome',
            condition_all: 'All records',
            condition_option_1: 'All conditions are met',
            condition_option_2: 'Any conditions are met',
            method_item_1: 'Disabled false',
            method_item_2: 'Disabled true',
            method_item_3: 'Display true',
            method_item_4: 'Display false',
            button_add: 'Add',
            button_dalete: 'Delete',
            coloring_option: 'Enable',
            button_submit: 'Save',
            button_cancel: 'Cancel',
            equal_to:'=(equal to)',
            not_equal_to:'≠(not equal to)',
            less_than: '≦(less than or equal to)',
            greater_than: '≧(greater than or equal to)',
            contain: 'contains',
            not_contain: 'does not contain',
            select_in: 'includes any of',
            select_notin: 'does not include any of',
            before: '<(before)',
            on_or_before: '≦(on or before)',
            after: '>(after)',
            on_or_after: '≧(on or after)',
            specify_date: '(Specify date)',
            specify_from_date: '(Specify days from today)',
            current: 'Current time',
            yesterday: 'Yesterday',
            today: 'Today',
            tomorrow: 'Tomorrow',
            last_week: 'Previous week',
            this_week: 'This week',
            next_week: 'Next week',
            last_month: 'Previous month',
            this_month: 'This month',
            next_month: 'Next month',
            last_year: 'Last year',
            this_year: 'This year',
            next_year: 'Next year',
            day: 'days',
            week: 'weeks',
            month: 'months',
            year: 'years',
            before_today: 'before today',
            after_today: 'after today',
            all_days: 'All days',
            sunday: 'Sunday',
            monday: 'Monday',
            tuesday: 'Tuesday',
            wednesday: 'Wednesday',
            thursday: 'Thursday',
            friday: 'Friday',
            saturday: 'Saturday',
            all: 'All days',
            date: '',
            last_day: 'End of month',
            selected: 'Selected',
            ken: '',
            user_placeholder: 'Specify ID separated by commas',
            error1: 'There is a blank in the outcome row.',
            error2: 'The following fields cannot be disabled. - Calculated, Field group, Table, Record number, Created by, Created datetime, Updated by, Updated datetime',
            error3: 'Fields in subtables cannot be disabled.'
        },
        zh: {
            label_1: '条件与处理',
            label_2: '条件字段着色',
            description_1: '设置字段的条件和过程（如果适用）。当满足多个条件时，上层进程具有优先权。',
            description_2: '将背景色添加到作为处理条件源的字段中。',
            table_th_1: '条件',
            table_th_2: '处理',
            condition_all: '所有记录',
            condition_option_1: '满足所有条件',
            condition_option_2: '满足任一条件',
            method_item_1: '可编辑的',
            method_item_2: '无法编辑',
            method_item_3: '显示',
            method_item_4: '隐',
            button_add: '添加',
            button_dalete: '删除',
            coloring_option: '启用',
            button_submit: '保存',
            button_cancel: '取消',
            equal_to:'=（等于）',
            not_equal_to:'≠（不等于）',
            less_than: '≦（小于等于）',
            greater_than: '≧（大于等于）',
            contain: '包含以下关键字',
            not_contain: '不包含以下关键字',
            select_in: '包含以下任意一个',
            select_notin: '不包含以下任意一个',
            before: '<（早于）',
            on_or_before: '≦（以前）',
            after: '>（晚于）',
            on_or_after: '≧（以后）',
            specify_date: '指定时间',
            specify_from_date: '今天起',
            current: '当前时间',
            yesterday: '昨天',
            today: '今天',
            tomorrow: '明天',
            last_week: '上周',
            this_week: '本周',
            next_week: '下周',
            last_month: '上个月',
            this_month: '本月',
            next_month: '下个月',
            last_year: '去年',
            this_year: '今年',
            next_year: '明年',
            day: '天',
            week: '周',
            month: '月',
            year: '年',
            before_today: '前',
            after_today: '后',
            all_days: '整周',
            sunday: '周日',
            monday: '周一',
            tuesday: '周二',
            wednesday: '周三',
            thursday: '周四',
            friday: '周五',
            saturday: '周六',
            all: '整月',
            date: '日',
            last_day: '月末',
            selected: '选择',
            ken: '个',
            user_placeholder: '指定ID，以逗号分隔',
            error1: '在处理列中有一个空白',
            error2: '以下字段不能被禁用 - 计算、组合、表格、记录编号、创建人、创建时间、更新人、更新时间',
            error3: '子表中的字段不能被禁用'
        }
    };
    window.kintoneplugin_lang = lang;